name: caja_herramientas
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - expat=2.7.1
  - libffi=3.4.4
  - openssl=3.0.17
  - pip=25.1
  - python=3.11.13
  - setuptools=78.1.1
  - sqlite=3.50.2
  - tk=8.6.14
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - altair==6.0.0
      - attrs==25.4.0
      - blinker==1.9.0
      - cachetools==6.2.2
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - click==8.3.1
      - colorama==0.4.6
      - contourpy==1.3.3
      - cycler==0.12.1
      - fonttools==4.61.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - holidays==0.86
      - idna==3.11
      - jinja2==3.1.6
      - joblib==1.5.2
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.9
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - narwhals==2.13.0
      - numpy==2.3.2
      - pandas==2.3.1
      - pillow==12.0.0
      - protobuf==6.33.2
      - pyarrow==22.0.0
      - pydeck==0.9.1
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - referencing==0.37.0
      - requests==2.32.5
      - rpds-py==0.30.0
      - scikit-learn==1.8.0
      - scipy==1.16.3
      - seaborn==0.13.2
      - six==1.17.0
      - smmap==5.0.2
      - streamlit==1.52.1
      - tenacity==9.1.2
      - threadpoolctl==3.6.0
      - toml==0.10.2
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - urllib3==2.6.1
      - watchdog==6.0.0
prefix: C:\Users\pablo\miniconda3\envs\caja_herramientas
